name: GCP

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    environment: gcp-prod
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/site:latest
    steps:
      # 1. Git checkout
      - name: Checkout
        uses: actions/checkout@v2

      # 2. Login to GCP
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 3. Configure Docker
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      # 4. GERA O ARQUIVO .ENV PRIMEIRO COM AS CHAVES DO SPARK
      - name: Generate .env file
        run: |
          echo "FIREBASE_API_KEY_ANDROID=${{ secrets.FIREBASE_API_KEY_ANDROID }}" >> .env
          echo "FIREBASE_API_KEY_IOS=${{ secrets.FIREBASE_API_KEY_IOS }}" >> .env
          echo "FIREBASE_API_KEY_WEB=${{ secrets.FIREBASE_API_KEY_WEB }}" >> .env
          echo "FIREBASE_APP_ID_ANDROID=${{ secrets.FIREBASE_APP_ID_ANDROID }}" >> .env
          echo "FIREBASE_APP_ID_IOS=${{ secrets.FIREBASE_APP_ID_IOS }}" >> .env
          echo "FIREBASE_APP_ID_WEB=${{ secrets.FIREBASE_APP_ID_WEB }}" >> .env
          echo "FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}" >> .env
          echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env
          echo "FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> .env

      # 5. CONSTROI A IMAGEM DOCKER (O Docker vai copiar o .env gerado acima)
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      # 6. PUSH PARA O GOOGLE CLOUD
      - name: Push Docker image
        run: docker push $IMAGE_NAME

      # 7. DEPLOY NO CLOUD RUN (Apenas as flags essenciais e a porta 80)
      - name: Deploy Docker image
        run: |
          gcloud run deploy site \
            --image $IMAGE_NAME \
            --region us-central1 \
            --memory 512Mi \
            --min-instances 0 \
            --max-instances 1 \
            --platform managed \
            --port 80 \
            --allow-unauthenticated
